import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { guard, isResponse } from '@/lib/api-guard'
import { sanitizeText } from '@/lib/security'

export const dynamic = 'force-dynamic'

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const g = await guard(req)
  if (isResponse(g)) return g
  const { id } = await params
  const ref = sanitizeText(id, 40)

  const client = await db.client.findFirst({
    where: { OR: [{ id: ref }, { clientId: ref }] },
    include: {
      lead: true,
      communications: { orderBy: { createdAt: 'desc' }, take: 100 },
      scopes: { orderBy: { version: 'desc' } },
      previews: { orderBy: { createdAt: 'desc' }, select: { id: true, token: true, version: true, status: true, viewCount: true, createdAt: true, sentAt: true, viewedAt: true, approvedAt: true } },
      payments: { orderBy: { createdAt: 'desc' } },
      invoices: { orderBy: { issuedAt: 'desc' } },
      meetings: { orderBy: { createdAt: 'desc' } },
      memories: { orderBy: { importance: 'desc' }, take: 50 },
      automationLogs: { orderBy: { startedAt: 'desc' }, take: 30 },
      approvals: { orderBy: { createdAt: 'desc' }, take: 30 },
      files: {
        where: { relatedType: { in: ['CLIENT_UPLOAD', 'ADMIN_SHARE'] } },
        orderBy: { createdAt: 'desc' },
        select: { id: true, originalName: true, mimeType: true, size: true, note: true, classification: true, scanStatus: true, scanResult: true, relatedType: true, uploadedBy: true, downloads: true, createdAt: true },
      },
    },
  })
  if (!client) return Response.json({ error: 'Client not found' }, { status: 404 })

  const projects = await db.project.findMany({
    where: { clientId: client.id },
    include: { tasks: { orderBy: { order: 'asc' } }, deliveries: true, handovers: true, reviews: true },
    orderBy: { createdAt: 'desc' },
  })

  // Unified timeline
  type Tl = { at: Date; type: string; text: string }
  const tl: Tl[] = []
  client.communications.forEach((c) => tl.push({ at: c.createdAt, type: `COMM_${c.channel}_${c.direction}`, text: `${c.direction === 'IN' ? 'Received' : 'Sent'} via ${c.channel}: ${(c.subject ?? c.body ?? '').slice(0, 140)}${c.status === 'FAILED' ? ' [FAILED]' : c.status === 'NOT_CONFIGURED' ? ' [NOT CONFIGURED]' : ''}` }))
  client.scopes.forEach((s) => tl.push({ at: s.createdAt, type: 'SCOPE', text: `Scope v${s.version} ${s.status} (generated by ${s.generatedBy ?? 'system'})` }))
  client.payments.forEach((p) => tl.push({ at: p.createdAt, type: 'PAYMENT', text: `Payment ${p.amount} ${p.currency} ${p.status}${p.verifiedAt ? ` verified by ${p.verifiedBy ?? 'admin'}` : ''}` }))
  client.meetings.forEach((m) => tl.push({ at: m.createdAt, type: 'MEETING', text: `Meeting ${m.status}: ${m.reason ?? ''}${m.scheduledAt ? ` — ${m.scheduledAt.toISOString().replace('T', ' ').slice(0, 16)} UTC` : ''}` }))
  client.approvals.forEach((a) => tl.push({ at: a.createdAt, type: 'APPROVAL', text: `Approval [${a.type}] ${a.status}: ${a.title}` }))
  client.memories.forEach((m) => tl.push({ at: m.createdAt, type: 'MEMORY', text: `Memory [${m.scope}] ${m.key}` }))
  client.automationLogs.forEach((l) => tl.push({ at: l.startedAt, type: 'AUTOMATION', text: `${l.workflow} ${l.status}` }))
  client.files.forEach((f) => tl.push({
    at: f.createdAt,
    type: 'DOCUMENT',
    text: `${f.relatedType === 'ADMIN_SHARE' ? 'Shared with client' : 'Client uploaded'}: ${f.originalName} (${f.scanStatus})`,
  }))
  projects.forEach((p) => {
    tl.push({ at: p.createdAt, type: 'PROJECT', text: `Project ${p.code} created (${p.status})` })
    p.tasks.forEach((t) => tl.push({ at: t.createdAt, type: 'TASK', text: `Task: ${t.title} (${t.status})` }))
  })
  tl.sort((a, b) => b.at.getTime() - a.at.getTime())

  const { communications, scopes, previews, payments, invoices, meetings, memories, automationLogs, approvals, files, lead, ...clientFields } = client
  return Response.json({
    client: clientFields,
    lead,
    communications,
    scopes: scopes.map((s) => ({ ...s, content: s.content })),
    previews,
    payments,
    invoices,
    meetings,
    memories,
    automationLogs,
    approvals,
    documents: files.map((f) => ({
      id: f.id,
      name: f.originalName,
      mimeType: f.mimeType,
      size: f.size,
      note: f.note,
      classification: f.classification,
      scanStatus: f.scanStatus,
      scanResult: f.scanResult ? safeParse(f.scanResult) : null,
      direction: f.relatedType === 'ADMIN_SHARE' ? 'SHARED' : 'UPLOADED',
      uploadedBy: f.uploadedBy,
      downloads: f.downloads,
      at: f.createdAt,
    })),
    projects,
    timeline: tl.slice(0, 200),
  })
}

function safeParse(s: string): unknown {
  try { return JSON.parse(s) } catch { return { raw: s.slice(0, 200) } }
}
