import { PrismaClient } from '@prisma/client'
const db = new PrismaClient()
async function main() {
  const agent = await db.aiAgent.findUnique({ where: { code: 'CST-020' }, select: { code: true, name: true, status: true, dailyQuota: true, tokensToday: true } })
  console.log('CST-020:', JSON.stringify(agent))
  const posts = await db.blogPost.findMany({ select: { slug: true, status: true, publishedAt: true }, orderBy: { publishedAt: 'desc' } })
  console.log('blog posts:', posts.length, JSON.stringify(posts.map(p => ({ s: p.slug, st: p.status, d: p.publishedAt?.toISOString()?.slice(0, 10) }))))
  const nlForms = await db.formSubmission.count({ where: { form: 'NEWSLETTER' } })
  console.log('NEWSLETTER form submissions:', nlForms)
  const nlEmails = await db.formSubmission.findMany({ where: { form: 'NEWSLETTER' }, select: { email: true, createdAt: true }, take: 20 })
  console.log('sample:', JSON.stringify(nlEmails))
  const subs = await db.newsletterSubscriber.count()
  console.log('NewsletterSubscriber rows:', subs)
  const camps = await db.emailCampaign.count()
  console.log('EmailCampaign rows:', camps)
  const events = await db.trackingEvent.groupBy({ by: ['name'], _count: true })
  console.log('tracking events by name:', JSON.stringify(events))
  const pv = await db.trackingEvent.findMany({ where: { name: 'page_view' }, select: { meta: true, anonId: true, path: true }, take: 5 })
  console.log('sample page_view events:', JSON.stringify(pv))
  const settings = await db.setting.findUnique({ where: { key: 'feature_flags' } })
  console.log('feature flags:', settings?.value)
  const clients = await db.client.count({ where: { deletedAt: null } })
  console.log('non-deleted clients:', clients)
}
main().finally(() => db.$disconnect())
